/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.SIG.view;

import com.SIG.controller.Controller;
import com.SIG.modelling.SalesInvoice;
import com.SIG.modelling.SalesInvoiceTableModel;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author Admin
 */
public class SIGframe extends javax.swing.JFrame {

    /**
     * Creates new form SIGframe
     */
    public SIGframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        salesinvoicetable = new javax.swing.JTable();
        createnewinvoiceButton = new javax.swing.JButton();
        createnewinvoiceButton.addActionListener(controller);
        deletecurrentinvoiceButton = new javax.swing.JButton();
        deletecurrentinvoiceButton.addActionListener(controller);
        salesinvoicenoLabel = new javax.swing.JLabel();
        salesinvoicedateLabel = new javax.swing.JLabel();
        clientnameLabel = new javax.swing.JLabel();
        totalpaymentLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        itemlInetable = new javax.swing.JTable();
        additemlineButton = new javax.swing.JButton();
        additemlineButton.addActionListener(controller);
        removeitemlineButton = new javax.swing.JButton();
        removeitemlineButton.addActionListener(controller);
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        loaddataMenuItem = new javax.swing.JMenuItem();
        loaddataMenuItem.addActionListener(controller);
        savedataMenuItem = new javax.swing.JMenuItem();
        savedataMenuItem.addActionListener(controller);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        salesinvoicetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(salesinvoicetable);

        createnewinvoiceButton.setText("Create New Invoice");

        deletecurrentinvoiceButton.setText("Delete Current Invoive");

        salesinvoicenoLabel.setText("Sales Invoice NO.");

        salesinvoicedateLabel.setText("Sales Invoice Date");

        clientnameLabel.setText("Client Name");

        totalpaymentLabel.setText("Total Payment");

        itemlInetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(itemlInetable);

        additemlineButton.setText("Add Item");

        removeitemlineButton.setText("Remove Item");

        jMenu1.setText("File");

        loaddataMenuItem.setText("Load Data");
        jMenu1.add(loaddataMenuItem);

        savedataMenuItem.setText("Save Data");
        jMenu1.add(savedataMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(createnewinvoiceButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deletecurrentinvoiceButton)
                        .addGap(48, 48, 48)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(additemlineButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(removeitemlineButton)
                                .addGap(22, 22, 22))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(salesinvoicedateLabel)
                                    .addComponent(totalpaymentLabel)
                                    .addComponent(clientnameLabel))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(salesinvoicenoLabel)
                                .addGap(51, 51, 51)
                                .addComponent(jLabel5)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salesinvoicenoLabel)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salesinvoicedateLabel)
                            .addComponent(jLabel6))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(clientnameLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(totalpaymentLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(deletecurrentinvoiceButton)
                        .addComponent(additemlineButton)
                        .addComponent(removeitemlineButton))
                    .addComponent(createnewinvoiceButton))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SIGframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SIGframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SIGframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SIGframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SIGframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton additemlineButton;
    private javax.swing.JLabel clientnameLabel;
    private javax.swing.JButton createnewinvoiceButton;
    private javax.swing.JButton deletecurrentinvoiceButton;
    private javax.swing.JTable itemlInetable;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem loaddataMenuItem;
    private javax.swing.JButton removeitemlineButton;
    private javax.swing.JLabel salesinvoicedateLabel;
    private javax.swing.JLabel salesinvoicenoLabel;
    private javax.swing.JTable salesinvoicetable;
    private javax.swing.JMenuItem savedataMenuItem;
    private javax.swing.JLabel totalpaymentLabel;
    // End of variables declaration//GEN-END:variables
   private ArrayList<SalesInvoice>invoices;
   private Controller controller = new Controller(this);
   private SalesInvoiceTableModel salesInvoiceTableModel;

    public ArrayList<SalesInvoice> getInvoices() {
        return invoices;
    }

    public void setInvoices(ArrayList<SalesInvoice> invoices) {
        this.invoices = invoices;
    }

    public SalesInvoiceTableModel getSalesInvoiceTableModel() {
        return salesInvoiceTableModel;
    }

    public void setSalesInvoiceTableModel(SalesInvoiceTableModel salesInvoiceTableModel) {
        this.salesInvoiceTableModel = salesInvoiceTableModel;
    }

    public JTable getItemlInetable() {
        return itemlInetable;
    }

    public JLabel getSalesinvoicedateLabel() {
        return salesinvoicedateLabel;
    }

    public JLabel getSalesinvoicenoLabel() {
        return salesinvoicenoLabel;
    }

    public JTable getSalesinvoicetable() {
        return salesinvoicetable;
    }

    public JLabel getTotalpaymentLabel() {
        return totalpaymentLabel;
    }

    public Controller getController() {
        return controller;
    }

    public JLabel getClientnameLabel() {
        return clientnameLabel;
    }
   
   

    
    
    
    
    
    
}
